### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by thewchan** [django-simple-deploy/django-simple-deploy#371]
In v0.8.0 it seems that `django-simple-deploy` depends on the 3 `dsd-` plugins but the 3 `dsd-` plugin also depends on `django-simple-deploy`. Seems like this is circular, and that `django-simple-deploy` should only _optionally_ depend on the 3 `dsd-` plugins.

**Comment by thewchan** [comment]
With this circular dependency we would indeed not be able to distribute either django-simple-deploy 0.8.0 nor any of the dsd plugins. The reason being 0.8.0 depends on the 3 (new) dsd plugins, which we would have to bring on board to conda forge first, but we will not be able to do so because they depend on django-simple-deploy 0.8.0, which depends on the 3 dsd plugins... and so forth.

**Comment by thewchan** [comment]
Broadly speaking, it seems to be if the 3 dsd- plugins is never intended to be installed without django-simple-deploy, and also that the newest version of django-simple-deploy should always be installed with the 3 dsd- plugins, then they should be bundled in the same library.

**Comment by thewchan** [comment]
In my experience, in other python libraries the pattern would be to make the plugins as optional dependencies, and raise an exception with hint text when the user tries to access parts of django-simple-deploy that requires the plugins to install them if they haven't already. An example of this would be pandas, which a very popular data science package, which has an optional dependency on xlrd, which allows it to interact with MS Excel files. It is an optional dependency not installed in the base installation. If the user try to use pandas to open an excel file, an exception is raised with the error text telling the user to install xlrd.

**Comment by ehmatthes** [comment]
Thanks, that's helpful. The plugins really need to be separate from the main package, because they need to be maintained on a separate timeline from the main package.

I may make them optional, and report to the user if the required one is not installed. But I really prefer making the project work in the default way just from installing django-simple-deploy.

One other approach I'm considering is to require these three plugins, but remove the django-simple-deploy requirement for each of the plugins. Non-default plugins would be free to require django-simple-deploy.

Do you think that would resolve packaging issues on your end? Also, do you have any sense of how often people are using conda to install Django? I have used condo occasionally, but not for quite some time.

**Comment by thewchan** [comment]
Thanks, either option should work. According to the conda-forge repo, so far django-simple-deploy had a little under 35k downloads: https://anaconda.org/conda-forge/django-simple-deploy

**Comment by ehmatthes** [comment]
Thanks, that's really helpful to know. I'm considering one other approach, and that's distinguishing requirements from dependencies. I think I'm going to try to set up conda forge locally and see if it builds locally before pushing an update.

**Comment by ehmatthes** [comment]
Hi again. I think this should work with 0.8.1. The core package no longer requires plugins.

I also set up a VM to re-render, so if there are still issues I should be more helpful in troubleshooting. I wasn't able to setup feedstocks for the plugins, but once they're set up I think I can rerender those locally to troubleshoot as needed.

Thanks for bringing this to my attention, and I'll let you close the issue when it's resolved.

**Comment by thewchan** [comment]
Thanks @ehmatthes; `0.8.1` is now available on Conda. https://anaconda.org/conda-forge/django-simple-deploy
I will work to distribute the 3 plugins there as well.

**Comment by ehmatthes** [comment]
This should be resolved now.

**Comment by thewchan** [comment]
Thanks so much @ehmatthes !
